name: isebushi_karaoke
description: "A new Flutter project."

# SDK制約を追加
environment:
  sdk: '^3.8.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.36
  record: ^6.0.0
  pitch_detector_dart: ^0.0.7
  permission_handler: ^11.0.1
  path_provider: ^2.1.1  # Phase 1で追加
  provider: ^6.1.1  # Phase 3: State management

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/splash/splash.png
    - assets/images/
    - assets/sounds/
    - assets/pitch/
    - assets/data/song.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/splash.png
  android_12:
    image: assets/splash/splash.png
    icon_background_color: "#ffffff"
    android_gravity: fill
  web: false

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
# flutter: このセクションは上記に統合済み

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  # uses-material-design: true このオプションは上記に移動済み

  # To add assets to your application, add an assets section, like this:
  # assets: このセクションは上記に統合済み

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
